import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import RepoProvider from "@/context/RepoContext";
import FileContextProvider from "@/context/SelectedFileContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<RepoProvider>
					<FileContextProvider>{children}</FileContextProvider>
				</RepoProvider>
			</body>
		</html>
	);
}
