import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import RepoProvider from "@/context/RepoContext";
import FileContextProvider from "@/context/SelectedFileContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<RepoProvider>
					<FileContextProvider>{children}</FileContextProvider>
				</RepoProvider>
				<ToastContainer
					position="top-right"
					autoClose={8000}
					hideProgressBar={false}
					newestOnTop={false}
					draggable={false}
					closeOnClick
					pauseOnHover
				/>
			</body>
		</html>
	);
}
