/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * FE-23 OpenAI API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  OpenAIResponse,
  OpenAIRequest,
  GetChatCompletionsParams
} from '.././model'


  
  /**
 * Given a list of messages comprising a conversation, the model will return a response.
 * @summary Completions
 */
export const getChatCompletions = (
    openAIRequest: OpenAIRequest,
    params?: GetChatCompletionsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OpenAIResponse>> => {
    return axios.post(
      `/chat/completions`,
      openAIRequest,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


